FROM starefossen/ruby-node:2-8-stretch
RUN apt-get update -qq && \
    apt-get install -y nano build-essential libpq-dev && \
    gem install bundler
RUN mkdir /dysphagiaassesment
COPY Gemfile Gemfile.lock /dysphagiaassesment/
WORKDIR /dysphagiaassesment
RUN bundle install
COPY . /dysphagiaassement
